version: '3'

services:
  derivco:
    image: derivco
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - derivco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    deploy:
      placement:
        constraints: [node.role == manager]
